
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class DialogueContent
{
    private readonly System.Collections.Generic.Dictionary<int, Dialogue> _dataMap;
    private readonly System.Collections.Generic.List<Dialogue> _dataList;
    
    public DialogueContent(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Dialogue>();
        _dataList = new System.Collections.Generic.List<Dialogue>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Dialogue _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.Dialogue.DeserializeDialogue(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Dialogue> DataMap => _dataMap;
    public System.Collections.Generic.List<Dialogue> DataList => _dataList;

    public Dialogue GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Dialogue Get(int key) => _dataMap[key];
    public Dialogue this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

