
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public DialogueContent DialogueContent {get; }
    public demo.Tbitem Tbitem {get; }
    public dialogue.TbA01 TbA01 {get; }
    public dialogue.TbA02 TbA02 {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        DialogueContent = new DialogueContent(loader("dialoguecontent"));
        Tbitem = new demo.Tbitem(loader("demo_tbitem"));
        TbA01 = new dialogue.TbA01(loader("dialogue_tba01"));
        TbA02 = new dialogue.TbA02(loader("dialogue_tba02"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        DialogueContent.ResolveRef(this);
        Tbitem.ResolveRef(this);
        TbA01.ResolveRef(this);
        TbA02.ResolveRef(this);
    }
}

}
