
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.dialogue
{
public sealed partial class A02 : Luban.BeanBase
{
    public A02(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Key"].IsString) { throw new SerializationException(); }  Key = _buf["Key"]; }
        { if(!_buf["ZN"].IsString) { throw new SerializationException(); }  ZN = _buf["ZN"]; }
        { if(!_buf["EN"].IsString) { throw new SerializationException(); }  EN = _buf["EN"]; }
    }

    public static A02 DeserializeA02(JSONNode _buf)
    {
        return new dialogue.A02(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// Key
    /// </summary>
    public readonly string Key;
    /// <summary>
    /// 中文
    /// </summary>
    public readonly string ZN;
    /// <summary>
    /// 英文
    /// </summary>
    public readonly string EN;
   
    public const int __ID__ = 1349849325;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Key:" + Key + ","
        + "ZN:" + ZN + ","
        + "EN:" + EN + ","
        + "}";
    }
}

}

