
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.dialogue
{
public partial class TbA02
{
    private readonly System.Collections.Generic.Dictionary<int, dialogue.A02> _dataMap;
    private readonly System.Collections.Generic.List<dialogue.A02> _dataList;
    
    public TbA02(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dialogue.A02>();
        _dataList = new System.Collections.Generic.List<dialogue.A02>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            dialogue.A02 _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.dialogue.A02.DeserializeA02(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, dialogue.A02> DataMap => _dataMap;
    public System.Collections.Generic.List<dialogue.A02> DataList => _dataList;

    public dialogue.A02 GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public dialogue.A02 Get(int key) => _dataMap[key];
    public dialogue.A02 this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

